version: "3"

volumes:
  superstreamer_redis_data:
  superstreamer_postgres_data:

services:
  superstreamer-api:
    image: "superstreamerapp/api:alpha"
    restart: always
    ports:
      - 52001:3000
    depends_on:
      - superstreamer-postgres
      - superstreamer-redis
    env_file: .env
    environment:
      - REDIS_URI=redis://superstreamer-redis:6379
      - DATABASE_URI=postgresql://postgres:sprs@superstreamer-postgres/sprs

  superstreamer-app:
    image: "superstreamerapp/app:alpha"
    ports:
      - 52000:3000
    environment:
      - PUBLIC_API_ENDPOINT=http://localhost:52001
      - PUBLIC_STITCHER_ENDPOINT=http://localhost:52002

  superstreamer-artisan:
    image: "superstreamerapp/artisan:alpha"
    restart: always
    depends_on:
      - superstreamer-redis
    env_file: .env
    environment:
      - REDIS_URI=redis://superstreamer-redis:6379

  superstreamer-stitcher:
    image: "superstreamerapp/stitcher:alpha"
    restart: always
    ports:
      - 52002:3000
    depends_on:
      - superstreamer-redis
    env_file: .env
    environment:
      - REDIS_URI=redis://superstreamer-redis:6379
      - PUBLIC_API_ENDPOINT=http://localhost:52001
      - PUBLIC_STITCHER_ENDPOINT=http://localhost:52002

  superstreamer-redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - superstreamer_redis_data:/data

  superstreamer-postgres:
    image: "postgres:latest"
    restart: always
    stop_signal: SIGINT
    ports:
      - "5432:5432"
    volumes:
      - superstreamer_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=sprs
      - POSTGRES_PASSWORD=sprs
