name = "sprs-stitcher"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
send_metrics = false

[vars]
KV = "cloudflare-kv"
PUBLIC_S3_ENDPOINT = "https://cdn.superstreamer.xyz"
PUBLIC_STITCHER_ENDPOINT = "https://stitcher.superstreamer.xyz"
PUBLIC_API_ENDPOINT = "https://api.tunnel.superstreamer.xyz"

[[kv_namespaces]]
binding = "kv"
id = "08ccfb81f250464ead5689f1e2b36432"